begin;
drop table if exists public.community_post_decks cascade;
drop table if exists public.flashcard_badge_unlocks cascade;
drop table if exists public.flashcard_xp_events cascade;
drop table if exists public.flashcard_deck_favorites cascade;
drop table if exists public.flashcard_deck_reports cascade;
drop table if exists public.flashcard_deck_ratings cascade;
drop table if exists public.flashcard_study_sessions cascade;
drop table if exists public.flashcard_user_progress cascade;
drop table if exists public.flashcards cascade;
drop table if exists public.flashcard_decks cascade;
drop function if exists public.set_flashcard_deck_favorite(uuid,boolean);
drop function if exists public.delete_flashcard_deck(uuid);
drop function if exists public.set_flashcard_star(uuid,boolean);
drop function if exists public.flashcard_badge_after_attachment();
drop function if exists public.flashcard_badge_after_deck_change();
drop function if exists public.flashcard_reward_summary();
drop function if exists public.complete_flashcard_session_v2(uuid,timestamptz,jsonb);
drop function if exists public.flashcard_unlock_badges(uuid);
drop function if exists public.flashcard_add_xp(uuid,text,integer,text,uuid,uuid);
drop function if exists public.flashcard_deck_rating_summary(uuid);
drop function if exists public.flashcard_assignment_decks(text);
drop function if exists public.link_flashcard_deck_assignment(uuid,text);
drop function if exists public.unlink_assignment_flashcards(text);
drop function if exists public.add_cards_to_owned_deck(uuid,jsonb);
drop function if exists public.attach_deck_to_community_post(uuid,uuid);
drop function if exists public.moderate_flashcard_deck(uuid,text,boolean);
drop function if exists public.flashcard_moderation_queue();
drop function if exists public.report_flashcard_deck(uuid,text,text);
drop function if exists public.rate_flashcard_deck(uuid,text);
drop function if exists public.flashcard_hide_after_reports();
drop function if exists public.complete_flashcard_session(uuid,timestamptz,jsonb);
drop function if exists public.copy_flashcard_deck(uuid);
drop function if exists public.flashcard_shared_decks(text,text,text,integer,integer);
drop function if exists public.flashcard_my_decks(text,text,text,integer,integer,text);
drop function if exists public.flashcard_my_decks(text,text,text,integer,integer);
drop function if exists public.flashcard_get_deck(uuid);
drop function if exists public.save_flashcard_deck(jsonb);
drop function if exists public.flashcard_touch();
drop function if exists public.flashcard_prepare_deck();
commit;
